#!/bin/bash
# bash pseudo strict mode
set -euo pipefail
IFS=$'\n\t'

mvn install:install-file -Dfile=lib/fscript-2.1.4-SNAPSHOT.jar -DgroupId=org.objectweb.fractal.fscript -DartifactId=fscript -Dversion=2.1.4-SNAPSHOT -Dpackaging=jar
mvn install:install-file -Dfile=lib/fscript-console-2.1.4-SNAPSHOT.jar -DgroupId=org.objectweb.fractal.fscript -DartifactId=fscript-console -Dversion=2.1.4-SNAPSHOT -Dpackaging=jar

mvn install:install-file -DpomFile=pom.xml -Dfile=dist/lib/ProActive-GCMScript.jar
